<../../mkconfig

TARG=\
	sunrpc.dis\
	portmaprpc.dis\
	mntrpc.dis\
#	nfsrpc.dis\

MODULES=\
	portmaprpc.m\
	mntrpc.m\
	nfsrpc.m\

SYSMODULES=\
	sys.m\
	bufio.m\
	sunrpc.m\

DISBIN=$ROOT/dis/lib

<$ROOT/mkfiles/mkdis
