<../../mkconfig

TARG=\
	portmapper.dis\
	nfssrv.dis\

MODULES=\
	../lib/portmaprpc.m\
	../lib/mntrpc.m\
	../lib/nfsrpc.m\

SYSMODULES=\
	sunrpc.m\
	arg.m\
	bufio.m\
	daytime.m\
	draw.m\
	keyring.m\
	string.m\
	sys.m\

DISBIN=$ROOT/dis

<$ROOT/mkfiles/mkdis
