<../../mkconfig

TARG=\
	portmapper.dis\
	nfssrv.dis\
	testportmap.dis\
	testmntrpc.dis\
	nfsfs.dis\

MODULES=\
	../lib/portmaprpc.m\
	../lib/mntrpc.m\
	../lib/nfsrpc.m\

SYSMODULES=\
	arg.m\
	bufio.m\
	daytime.m\
	draw.m\
	string.m\
	sys.m\
	tables.m\
	util0.m\
	sunrpc.m\
	portmap.m\

DISBIN=$ROOT/dis

<$ROOT/mkfiles/mkdis
